### ISSUE TITLE
QID-1964-MVAsvmOrangePeel - code doesn't work

### ISSUE THREAD

**Issue by polarstern** [QuantLet/Q-Problems#19]
Error in res1[i, j] <- kernel(x[i, ], x[j, ]) : 
  number of items to replace is not a multiple of replacement length

Error in plot(OrangePeelModel, data = OrangePeel, xlim = c(-3.5, 3.5),  : 
  error in evaluating the argument 'x' in selecting a method for function 'plot': Error: object 'OrangePeelModel' not found

**Comment by awdesch** [comment]
Code runs perfectly fine. Maybe there is an issue with the R-version or OS you've used.

**Comment by lborke** [comment]
no problems on my PC

**Comment by polarstern** [comment]
Now it works fine...
